---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.143240'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Encode-DIN66003
no_index:
  directory:
    - t
    - inc
requires:
  Encode: '1.41'
  charnames: '0'
resources:
  repository: git://github.com/Corion/Encode-DIN66003.git
version: '0.03'
