---
abstract: 'Encoding according to DIN 66003'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.143240'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Encode-DIN66003
no_index:
  directory:
    - t
    - inc
requires:
  Encode: '1.41'
  charnames: '0'
  perl: '5.006'
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/Corion/Encode-DIN66003.git
version: '0.03'
